### PR TITLE
Don't trigger build when only editing readme

### PR DESCRIPTION
**Pull request by MarcDenman**

### CODE REVIEW

**Review by elduddz — COMMENTED** [review]
👍

**Review by elduddz — COMMENTED** [review]
👍

**Review by elduddz — APPROVED** [review]
all good, not sure why I cannot review?

**Comment by MarcDenman** [comment]
Do not merge.

**Comment by elduddz** [comment]
ok

**Review by elduddz — CHANGES_REQUESTED** [review]
can I change my review?

**Comment by MarcDenman** [comment]
Closing as not sure this is relevant anymore

**Pull request closed without merging**
